**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [7]:
#Code here
vector = np.zeros(10)
vector[[0, 1, 2, 3, 5, 6, 7, 8, 9]] = np.nan
vector[4] = 1
print(vector)



[nan nan nan nan  1. nan nan nan nan nan]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [11]:
#Code here

a = int(input("Enter first dimension: "))
b = int(input('Enter second dimension: '))

arr = np.random.random((a, b))
avg = np.mean(arr)
print(avg)

0.5728734559979412


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [17]:
#Code here
def ones_and_zeros(a, b):
    arr = np.zeros((a, b))
    arr[[0, -1], :] = 1 
    arr[:, [0, -1]] = 1
    return arr 

ones_and_zeros(6,3)


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [23]:
#Code here
np.random.rand(1, 10)

array([[0.31949576, 0.39556819, 0.11806312, 0.43888278, 0.58872109,
        0.02200004, 0.8934233 , 0.90724929, 0.56608611, 0.03215056]])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [24]:
#Code here
np.random.randint(0, 4, 25).reshape(5, 5)

array([[3, 1, 1, 0, 2],
       [2, 1, 0, 3, 1],
       [3, 0, 1, 1, 2],
       [2, 0, 3, 0, 0],
       [2, 0, 1, 1, 2]], dtype=int32)

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [37]:
#code here
cord = np.random.randint(1, 100, 20).reshape(10, 2)
point = np.array([2, 3])
np.astype(np.sqrt((cord[:, 0] - point[0]) ** 2 + (cord[:, 1] - point[1]) ** 2), int)


array([ 68,  17,  95,  93,  74, 101,  52,  95,  84,  72])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
#Code here
np.arange(336).reshape(6, 7, 8)[1, 5, 3]

np.int64(99)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [48]:
#Code here
lst = '1 2 3 4 -8 10'
np.array(list(reversed(list(map(int, lst.split())))))


array([10, -8,  4,  3,  2,  1])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [50]:
#Code here
arr = np.array([12, 2, 3, 1])
print('elements_count: ', len(arr))

elements_count:  4


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [53]:
#Code here
def softmax(arr: np.ndarray):
    if arr.ndim != 1:
        raise f'dimension should be equal to one but got {arr.ndim}'
    num = np.exp(arr)
    den = np.sum(num)
    return num / den

softmax(np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098 , 68.82830233 , 91.52064278]))
    

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [64]:
#Coder here

def vstack(*args: np.ndarray) -> np.ndarray:

    res = args[0]
    for arr in args[1:]:
        if not isinstance(arr, np.ndarray):
            raise "array not found."
        res = np.vstack((res, arr))

    return res 

a= np.array([[0, 1,2, 3, 4],
 [5 ,6 ,7 ,8 ,9]])

b= np.array([[1, 1, 1, 1, 1],
 [1 ,1 ,1 ,1 ,1]])

c= np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567 ,0.13502419 ,0.55692335 ,0.16479622 ,0.61193593]])

vstack(a, b, c)


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [67]:
#Code here
from datetime import datetime 
def date_array(start: str, end: str):
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError('Both arguments must be string')
    
    date_format = '%Y-%m-%d'

    try:
        start_date = datetime.strptime(start, date_format)
        end_date = datetime.strptime(end, date_format)
    except ValueError:
        raise ValueError(f'Dates must match the format {date_format}')


    dates = np.arange(
        np.datetime64(start_date.date()),
        np.datetime64(end_date.date() + np.timedelta64(1, 'D')
    )
    )

    return dates 

date_array(start='2020-11-26', end='2020-11-30')


array(['2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29',
       '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [68]:
#code here
matrix = np.random.randint(1, 100, 24).reshape(6, 4)
matrix

array([[87, 20, 99, 15],
       [20, 19, 15, 72],
       [34,  3,  4, 52],
       [46,  1, 15, 72],
       [ 8, 94, 18, 81],
       [55, 49,  5, 72]], dtype=int32)

In [69]:
mean = matrix.mean(axis=1)
mean

array([55.25, 31.5 , 23.25, 33.5 , 50.25, 45.25])

In [71]:
mean.reshape(6, -1)

array([[55.25],
       [31.5 ],
       [23.25],
       [33.5 ],
       [50.25],
       [45.25]])

In [73]:
matrix - mean.reshape(6, -1)

array([[ 31.75, -35.25,  43.75, -40.25],
       [-11.5 , -12.5 , -16.5 ,  40.5 ],
       [ 10.75, -20.25, -19.25,  28.75],
       [ 12.5 , -32.5 , -18.5 ,  38.5 ],
       [-42.25,  43.75, -32.25,  30.75],
       [  9.75,   3.75, -40.25,  26.75]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [81]:
#Code here
arr = np.arange(24).reshape(6, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
arr[:, [0, 1]] = arr[:, [1, 0]]


In [83]:
print(arr)

[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]
 [13 12 14 15]
 [17 16 18 19]
 [21 20 22 23]]


###`Q-16:` Replace odd elements in arrays with -1.

In [84]:
#Code here
arr = np.arange(24).reshape(6, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [85]:
np.where(arr % 2 == 0, arr, -1)

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1],
       [12, -1, 14, -1],
       [16, -1, 18, -1],
       [20, -1, 22, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [86]:
#Code here
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])
np.where(a >= b, a, b) 


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [87]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9495, 5050, 3839, 2748, 2733],
       [ 973, 4379, 5422, 6682, 7894],
       [2772, 8941, 9704, 7976, 7040],
       [7246, 9141, 2139, 2468, 3120],
       [7526, 7877, 5202, 7043, 1086],
       [6127, 1093, 1993, 8812, 6604],
       [7734, 5550, 2662, 1449, 9221],
       [3380, 8815, 9857, 9399, 2311]], dtype=int32)

In [88]:
#Code here
arr1[:, np.arange(0, arr1.shape[1]+1, 2)]

array([[9495, 3839, 2733],
       [ 973, 5422, 7894],
       [2772, 9704, 7040],
       [7246, 2139, 3120],
       [7526, 5202, 1086],
       [6127, 1993, 6604],
       [7734, 2662, 9221],
       [3380, 9857, 2311]], dtype=int32)

In [93]:
(arr1 - np.min(arr1, axis=0)) / (np.max(arr1, axis=0) - np.min(arr1, axis=0))

array([[1.        , 0.49167495, 0.23474059, 0.16339623, 0.20245851],
       [0.        , 0.4083002 , 0.43603764, 0.65823899, 0.83687769],
       [0.21110068, 0.97514911, 0.98054425, 0.82100629, 0.7318992 ],
       [0.73609481, 1.        , 0.01856562, 0.1281761 , 0.25003073],
       [0.76895095, 0.84294235, 0.40806205, 0.7036478 , 0.        ],
       [0.60478761, 0.        , 0.        , 0.92616352, 0.67830363],
       [0.79335837, 0.55380219, 0.08507121, 0.        , 1.        ],
       [0.28244544, 0.95949304, 1.        , 1.        , 0.1505839 ]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [94]:
#Code here
def get_nth_largest(arr, n):
    # Ensure n is within the bounds of the array
    if n > len(arr) or n <= 0:
        raise ValueError("n must be between 1 and the length of the array.")
    
    # Sort the array in ascending order
    sorted_arr = np.sort(arr)
    
    # Return the nth item from the end
    return sorted_arr[-n]

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [104]:
#code here
a = np.array([1, 2, 3])
x = a.reshape(3, -1)
np.ravel(np.vstack((np.hstack((x,x,x)), a, a, a)))




array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])