### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

Creating Numpy Arrays

In [2]:
# np.array

import numpy as np

np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
# 2D and 3D 
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([[[1, 2, 3]], [[4, 5, 6]]])

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [8]:
# dtype 

print(np.array([1, 2, 3, 4], dtype='float'))
print(np.array([1, 2, 3, 4], dtype='bool'))
print(np.array([1, 2, 3, 4], dtype='complex'))

[1. 2. 3. 4.]
[ True  True  True  True]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [10]:
# np.arange
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [11]:
# with reshape

a = np.array([1, 2, 3, 4, 5, 6])
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# np.ones and np.zeros
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [15]:
# np.random
np.random.random((3, 4))

array([[0.86619042, 0.49913168, 0.39797745, 0.67064516],
       [0.44002055, 0.53027964, 0.15113173, 0.48683698],
       [0.36632218, 0.94197513, 0.52849646, 0.34877306]])

In [3]:
# np.linspace

import numpy as np
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
# np.identity 

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [7]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)


In [ ]:
# ndim
print(a1.ndim, 'D')
print(a2.ndim, 'D')
print(a3.ndim, 'D')

1 D
2 D
3 D


In [10]:
# shape 
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size  # no of items in an array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [12]:
# itemsize

a1.itemsize

8

In [13]:
a2.itemsize

8

In [15]:
a3.itemsize # 8 bytes

8

In [16]:
# dtype

a1.dtype


dtype('int64')

Changing DataType

In [17]:
# astype 
a3.dtype

dtype('int64')

In [18]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [19]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

In [20]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 + 4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [30]:
# relational
a1 > 5 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [31]:
# vector operations

# arithmetic
a1 + a2 

array([[35.34831341, 60.60262509, 99.98633903],
       [25.24999314, 64.63686692, 30.30126797],
       [74.74095085, 38.38340167, 27.26741025]])

In [32]:
a1 * a2

array([[12.19096926, 36.15750511, 97.64756355],
       [ 6.24982846, 40.75948304,  9.0380392 ],
       [54.83036278, 14.56926358,  7.22007674]])

In [33]:
a1 / a2

array([[0.00995181, 0.01004375, 0.00996302],
       [0.00999973, 0.00995105, 0.01004227],
       [0.01001285, 0.01008952, 0.00990408]])

Array Functions

In [34]:
a1 = np.random.random((3, 3))
a2 = np.round(a1 * 100)
print(a1)
print(a2)

[[0.45745673 0.1319676  0.45092522]
 [0.62955154 0.04640798 0.05826888]
 [0.43467033 0.32719021 0.58560903]]
[[46. 13. 45.]
 [63.  5.  6.]
 [43. 33. 59.]]


In [38]:
# max/min/sum/prod
print(np.max(a2))
print(np.min(a2))
print(np.sum(a2))
print(np.prod(a2))

63.0
5.0
313.0
4258041687900.0


In [39]:
# max/min/sum/prod in each row
a2

array([[46., 13., 45.],
       [63.,  5.,  6.],
       [43., 33., 59.]])

In [40]:
np.max(a2, axis=1)

array([46., 63., 59.])

In [41]:
np.min(a2, axis=1)

array([13.,  5., 33.])

In [42]:
np.sum(a2, axis=1)

array([104.,  74., 135.])

In [43]:
np.prod(a2, axis=1)

array([26910.,  1890., 83721.])

In [46]:
# mean/median/std/var

np.mean(a1), np.mean(a1, axis=1)

(np.float64(0.34689416811063106), array([0.34678318, 0.2447428 , 0.44915652]))

In [47]:
# trignometric functions
np.sin(a1)

array([[0.44166777, 0.13158489, 0.43579846],
       [0.58878233, 0.04639132, 0.05823591],
       [0.42111141, 0.32138358, 0.55270703]])

In [48]:
# dot product 
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)



In [50]:
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [49]:
np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [51]:
# log and exponents 
np.log(a1)

array([[-0.78207298, -2.02519885, -0.79645376],
       [-0.46274756, -3.07028394, -2.8426872 ],
       [-0.83316739, -1.11721359, -0.5351029 ]])

In [52]:
np.exp(a1)

array([[1.58005038, 1.14107135, 1.56976389],
       [1.87676873, 1.04750168, 1.05999997],
       [1.54445382, 1.38706529, 1.79608451]])

In [55]:
# round/floor/ceil

np.round(np.random.random((2, 3)))

array([[0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.floor(np.random.random((2, 3)))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ceil(np.round(np.random.random((2, 3))))

array([[1., 1., 1.],
       [1., 1., 0.]])

Indexing / Slicing

In [58]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# last element
a1[-1]

np.int64(9)

In [61]:
# first element
a1[0]

np.int64(0)

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
# fetch 6 
a2[1, 2]

np.int64(6)

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
# fetch 5 
a3[1, 0, 1]

np.int64(5)

In [67]:
# slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# fetch 2, 3, 4
a1[2:5]

array([2, 3, 4])

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
# fetch 1st row
a2[0, :]

array([0, 1, 2, 3])

In [72]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
a3 = np.arange(27).reshape(3, 3, 3)

In [74]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
a3[1, :, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [76]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [77]:
a3[0, 1]

array([3, 4, 5])

In [78]:
a3[1, :, 1]

array([10, 13, 16])

Iterating

In [82]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [83]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [84]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [85]:
# fetch each element
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [86]:
# reshape


In [87]:
# Transpose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [89]:
# ravel - flatten
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking

In [90]:
# horizontal stacking
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)



In [92]:
np.hstack((a4, a5, a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [93]:
# vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [94]:
# horizontal splitting

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [96]:
# vertical spliting
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]