np.sort

Return a sorted copy of an array

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1, 100, 15)
a

array([38, 14, 98, 93, 62, 25, 68, 70, 54,  4,  2, 28, 14, 79,  7],
      dtype=int32)

In [4]:
a.sort()

In [5]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [6]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[43, 35,  9, 61],
       [25, 66, 61, 92],
       [42, 82, 38, 21],
       [80,  5, 23, 82],
       [42,  2, 45, 95],
       [27,  3, 55, 87]], dtype=int32)

In [9]:
b.sort(axis=1) # sorting rows

In [10]:
b

array([[ 9, 35, 43, 61],
       [25, 61, 66, 92],
       [21, 38, 42, 82],
       [ 5, 23, 80, 82],
       [ 2, 42, 45, 95],
       [ 3, 27, 55, 87]], dtype=int32)

In [11]:
np.sort(b)

array([[ 9, 35, 43, 61],
       [25, 61, 66, 92],
       [21, 38, 42, 82],
       [ 5, 23, 80, 82],
       [ 2, 42, 45, 95],
       [ 3, 27, 55, 87]], dtype=int32)

In [12]:
b = np.random.randint(1, 100, 24).reshape(6, 4)

In [13]:
b

array([[67, 50, 41, 31],
       [84, 52, 86, 79],
       [47, 83, 48, 89],
       [71, 72, 52, 35],
       [65, 35, 86, 89],
       [23, 70,  4, 75]], dtype=int32)

In [14]:
np.sort(b)

array([[31, 41, 50, 67],
       [52, 79, 84, 86],
       [47, 48, 83, 89],
       [35, 52, 71, 72],
       [35, 65, 86, 89],
       [ 4, 23, 70, 75]], dtype=int32)

np.append

The numpy.append() appends values along the mentioned axis at the end of existing axis.

In [15]:
a 

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [16]:
np.append(a, 200)

array([  2,   4,   7,  14,  14,  25,  28,  38,  54,  62,  68,  70,  79,
        93,  98, 200])

In [17]:
b

array([[67, 50, 41, 31],
       [84, 52, 86, 79],
       [47, 83, 48, 89],
       [71, 72, 52, 35],
       [65, 35, 86, 89],
       [23, 70,  4, 75]], dtype=int32)

In [22]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[67., 50., 41., 31.,  1.],
       [84., 52., 86., 79.,  1.],
       [47., 83., 48., 89.,  1.],
       [71., 72., 52., 35.,  1.],
       [65., 35., 86., 89.,  1.],
       [23., 70.,  4., 75.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [23]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [24]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method

In [25]:
e = np.array([1, 1, 2, 2, 3, 3])
np.unique(e)

array([1, 2, 3])

np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.

In [26]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [28]:
np.expand_dims(a, axis=0)

array([[ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98]],
      dtype=int32)

np.where()

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [29]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [30]:
# find all indices with value greater than 50 
np.where(a > 50)

(array([ 8,  9, 10, 11, 12, 13, 14]),)

In [31]:
# replace all values > 50 with 0 
np.where(a > 50, 0, a)

array([ 2,  4,  7, 14, 14, 25, 28, 38,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

np.argmax

the numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [32]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [33]:
np.argmax(a)

np.int64(14)

In [34]:
b

array([[67, 50, 41, 31],
       [84, 52, 86, 79],
       [47, 83, 48, 89],
       [71, 72, 52, 35],
       [65, 35, 86, 89],
       [23, 70,  4, 75]], dtype=int32)

In [36]:
np.argmax(b, axis=1)

array([0, 2, 3, 1, 3, 3])

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [37]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [38]:
np.cumsum(a)

array([  2,   6,  13,  27,  41,  66,  94, 132, 186, 248, 316, 386, 465,
       558, 656])

np.percentile

numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [39]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [40]:
np.percentile(a, 50)

np.float64(38.0)

In [41]:
np.median(a)

np.float64(38.0)

np.histogram


In [42]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [43]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([3, 2, 2, 1, 0, 1, 2, 2, 0, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef

Return Pearson product moment correlation coefficients.

In [44]:
salary = np.array([20000, 40000, 25000, 35000, 60000 ])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

with the help of np.isin() method, we can see that one array having values are checked in a different array having different elements with different sizes.

In [45]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [47]:
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
a[np.isin(a, items)]

array([70], dtype=int32)

np.flip() 

reverses the order of array elements along the specified axis, preserving the shape of the array.


In [48]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [49]:
np.flip(a)

array([98, 93, 79, 70, 68, 62, 54, 38, 28, 25, 14, 14,  7,  4,  2],
      dtype=int32)

np.put()

replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [50]:
a

array([ 2,  4,  7, 14, 14, 25, 28, 38, 54, 62, 68, 70, 79, 93, 98],
      dtype=int32)

In [51]:
np.put(a, [0, 1], [110, 530])

In [52]:
a

array([110, 530,   7,  14,  14,  25,  28,  38,  54,  62,  68,  70,  79,
        93,  98], dtype=int32)

np.delete()

returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [53]:
a

array([110, 530,   7,  14,  14,  25,  28,  38,  54,  62,  68,  70,  79,
        93,  98], dtype=int32)

In [54]:
np.delete(a, 0)

array([530,   7,  14,  14,  25,  28,  38,  54,  62,  68,  70,  79,  93,
        98], dtype=int32)

np.clip()

clip (limit) the values in an array

In [55]:
a

array([110, 530,   7,  14,  14,  25,  28,  38,  54,  62,  68,  70,  79,
        93,  98], dtype=int32)

In [56]:
np.clip(a, 25, 75)

array([75, 75, 25, 25, 25, 25, 28, 38, 54, 62, 68, 70, 75, 75, 75],
      dtype=int32)